[tool.distutils.egg_info]
egg_base = '/tmp/jffe_build'

[tool.isort]
profile = 'black'
skip_gitignore = true
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
line_length = 88

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.pytest.ini_options]
minversion = '6.0'
cache_dir = '/tmp/pytest_cache'
asyncio_mode = 'auto'
markers = [
    'asyncio',
]
testpaths = [
    'tests',
]
